name: video_player_web
description: Web platform implementation of video_player and supports hls on chrome and other browsers.
homepage: https://github.com/deckblue/video_player_web
version: 1.3.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VideoPlayerPlugin
        fileName: video_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.0.0
  video_player_platform_interface: ^6.2.0
  web: ">=1.0.0 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"
